### ISSUE TITLE
Suggestion: Saving personal settings

### ISSUE THREAD

**Issue by WrecksBG** [loljoshie/lj-menu#2]
Will be awesome if you make all settings which player make to save into players table

**Comment by Skillgjii** [comment]
+1

**Comment by sinfuljosh** [comment]
Use Native KVP instead. It stores it locally on that system (so if you play on different systems it allows you to configure each one separately), and as long as you dont attempt to rename the resources then the settings stay. And no requirement on the database, because its stores this all natively. 

When the value is a string
SetResourceKvp - https://docs.fivem.net/natives/?_0x21C7A35B
GetResourceKvpString - https://docs.fivem.net/natives/?_0x5240DA5A

When the value is an int
SetResourceKvpInt - https://docs.fivem.net/natives/?_0x6A2B1E8
GetResourceKvpInt - https://docs.fivem.net/natives/?_0x12B8D689


When the value is a float
SetResourceKvpFloat - https://docs.fivem.net/natives/?_0x9ADD2938
GetResourceKvpFloat - https://docs.fivem.net/natives/?_0x35BDCEEA

And if you need a working example. Kibook uses it on his "No Idle Cam" resource. https://github.com/kibook/NoIdleCam/blob/main/client.lua
